apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-app
  template:
    metadata:
      labels:
        app: limit-app
    spec:
      containers:
        - name: limit-api
          image: sandeepkjl143/limit-image:latest
