apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-app
  template:
    metadata:
      labels:
        app: limit-app
    spec:
      containers:
        - name: limit-api
          image: sandeepkjl143/limit-image:latest
        - name: mysqldb
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Sandeep@123
            - name: MYSQL_DATABASE
              value: paymentdb
